// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBboO4ex95jUPbcWZDEWuT-haljpeY1OaU',
    appId: '1:579162621803:web:f0c08674767a02854dae2e',
    messagingSenderId: '579162621803',
    projectId: 'focus-app-v2-finalkerem',
    authDomain: 'focus-app-v2-finalkerem.firebaseapp.com',
    storageBucket: 'focus-app-v2-finalkerem.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfBBjIEVj0o8j4uzA5aBVdOLve__9RwBc',
    appId: '1:579162621803:android:2296944cce3893e84dae2e',
    messagingSenderId: '579162621803',
    projectId: 'focus-app-v2-finalkerem',
    storageBucket: 'focus-app-v2-finalkerem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5L1WkFBzi9zHuFOIQz3Jz1u11Qqamuic',
    appId: '1:579162621803:ios:b4fd2d076344c86f4dae2e',
    messagingSenderId: '579162621803',
    projectId: 'focus-app-v2-finalkerem',
    storageBucket: 'focus-app-v2-finalkerem.firebasestorage.app',
    iosBundleId: 'com.example.focusAppV2Final',
  );
}
